/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

#import <AppKit/AppKit.h>

int main(int argc, char *argv[]) {

    [NSApplication sharedApplication];
    if ([NSBundle loadNibNamed:@"QuakeEd" owner:NSApp])
	    [NSApp run];
	    
    [NSApp release];
    return EXIT_SUCCESS;
}
